# Generated by Django 6.0.4 on 2026-04-18 16:53

import apps.payments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(db_index=True, default=apps.payments.models.generate_idempotency_key, editable=False, help_text='Unique key to prevent duplicate payment processing', unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number in E.164 format (254XXXXXXXXX)', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in KES', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Human-readable reason for failure, if applicable')),
                ('mpesa_merchant_request_id', models.CharField(blank=True, default='', help_text='Merchant request ID from STK push response', max_length=100)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, db_index=True, default='', help_text='Checkout request ID — used to match the M-Pesa callback', max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', help_text='M-Pesa receipt number (e.g. QKS4Y5NLMN) — proof of payment', max_length=50)),
                ('mpesa_response_code', models.CharField(blank=True, default='', help_text='Result code from M-Pesa callback (0 = success)', max_length=10)),
                ('mpesa_response_description', models.CharField(blank=True, default='', help_text='Human-readable result description from M-Pesa', max_length=255)),
                ('callback_raw', models.JSONField(blank=True, help_text='Full raw callback payload from M-Pesa — for auditing', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times we have retried this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_transaction_status_created'), models.Index(fields=['phone_number', 'created_at'], name='idx_transaction_phone_created')],
            },
        ),
    ]
